import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [


  // รายงาน
  // {
  //   path: "",
  //   title: "รายงาน",
  //   moduleName: "report",
  //   iconType: "material-icons-two-tone",
  //   icon: "content_paste",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [
  //     {
  //       path: "/report/deposit",
  //       title: "ฝากเงิน",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/report/withdraw",
  //       title: "ถอนเงิน",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/report/upcredit",
  //       title: "อัพเครดิต",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/report/winloss",
  //       title: "ยอดได้-เสีย(win loss)",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/report/totalcredit",
  //       title: "เครดิตรวมทั้งหมด",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/report/sum",
  //       title: "สรุปยอดรวม",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/report/test",
  //       title: "test",
  //       moduleName: "report",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     // {
  //     //   path: "/report/test2",
  //     //   title: "test2",
  //     //   moduleName: "report",
  //     //   iconType: "",
  //     //   icon: "",
  //     //   class: "ml-menu",
  //     //   groupTitle: false,
  //     //   badge: "",
  //     //   badgeClass: "",
  //     //   role: [""],
  //     //   submenu: [],
  //     // },
  //     // {
  //     //   path: "/report/test3",
  //     //   title: "test3",
  //     //   moduleName: "report",
  //     //   iconType: "",
  //     //   icon: "",
  //     //   class: "ml-menu",
  //     //   groupTitle: false,
  //     //   badge: "",
  //     //   badgeClass: "",
  //     //   role: [""],
  //     //   submenu: [],
  //     // },
  //   ],
  // },
];
